### ISSUE TITLE
Add dependency in hinemos-6.0-manager

### ISSUE THREAD

**Issue by okamototk** [hinemos/hinemos#2]
Hi, 

Please add selinux-policy package to rpm dependency for hinemos-6.0-manager-6.0.0-1.el7.x86_64.rpm package.

I got following error while installing Hinemos on Docker CentOS containder,
It /usr/sbin/getenforce command is in selinux-policy package. Please add it in dependency.

[root@hinemos /]# rpm -Uvh hinemos-6.0-manager-6.0.0-1.el7.x86_64.rpm
Preparing...                          ################################# [100%]
/var/tmp/rpm-tmp.Rwt2d8: line 15: /usr/sbin/getenforce: No such file or directory
Installation failed.
Please disable SELinux.
error: %pre(hinemos-6.0-manager-0:6.0.0-1.el7.x86_64) scriptlet failed, exit status 255
error: hinemos-6.0-manager-0:6.0.0-1.el7.x86_64: install failed

**Comment by hinemos-geek** [comment]
Oops! Thanks so much for reporting.
We will try to fix this problem ASAP and release in the next minor version.

BTW, if you need a patch in advance, you can also contact our support member by filling the following form.
URL: https://www.hinemos.info/estimate (currently Japanese only)

**Comment by hinemos-geek** [comment]
Dear @okamototk,
 I am very pleased to inform you that this SELinux check problem has been fixed in ver.6.0.1, which is freshly released just now.
You can find more details from the ver.6.0.1 release note [here](https://github.com/hinemos/hinemos/releases/tag/v6.0.1).

Please give it a try and we are looking forward to hearing your feedback soon.
