### ISSUE TITLE
resource graph of Windows on VM can't indicate

### ISSUE THREAD

**Issue by conp889** [hinemos/hinemos#4]
Hello,

A resource graph of Windows on VM can't indicate.
(Further, It can be indicated in RHEL.)

ex.
Performance(Graph) > Root > Manager > OS Scope(OS) > Windows(WINDOWS) > File system usage
Item Name: CPU Usage

When I have pushed [Apply] button,  the following message is indicated.

error
An unexpected error occurred. : Failed to evaluate javascript expression

* Enviroment
 HyperViosr : ESXi 6.0u2

- Manager
 OS : RHEL7.3(VM)
 Hinemos 6.0.1
 java-1.8.0.141-3-openjdk

- Target(Agent)
 OS: Windows Server 2012R2(VM)
 Oracle Java SE 8u131

**Comment by hinemos-geek** [comment]
> Performance(Graph) > Root > Manager > OS Scope(OS) > Windows(WINDOWS) > File system usage
> Item Name: CPU Usage

First, I assume that this issue occurred when you are trying to open a performance graph for the file system result.

> An unexpected error occurred. : Failed to evaluate javascript expression

The error above is caused by the unexpected backslash (\\) of the windows file system path (i.e. C:\\).

This is a reported issue and it will be fixed in the next minior release 6.0.2.
BTW, 6.0.2 is planned to be released on 20th this month (October 20, 2015).

**Comment by conp889** [comment]
> The error above is caused by the unexpected backslash (\) of the windows file system path (i.e. C:\).
I see.

> This is a reported issue and it will be fixed in the next minior release 6.0.2.
> BTW, 6.0.2 is planned to be released on 20th this month (October 20, 2015).
It's expected of "6.0.2".

BTW, is it update possible in [ #rpm -Uvh ] to 6.0.2 from 6.0.1 ?

**Comment by conp889** [comment]
This problem solved with update from v6.0.1 to v6.0.2. Thanks.
